server:
  port: 3030
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: temporal-seed
  # temporal specific configs
  temporal:
    connection:
      namespace: my-cloud-namespace.accountid
    # namespace: default
      target: my-cloud-namespace.accountid.tmprl.cloud:7233
    # target: local     # specifying local is equivalent to WorkflowServiceStubs.newLocalServiceStubs() so all other connection options are ignored.
      enable-https: true
      mtls:
        key-file: /path/to/cert.key
        cert-chain-file: /path/to/cert.pem
      # key-password: <password-for-the-key>
      # insecure-trust-manager: true # or add cert.pem to java default truststore
      workers:
        - task-queue: weird-task-queue
        # name: your-worker-name # unique name of the Worker. If not specified, Task Queue is used as the Worker name.
          workflow-classes:
            - your.package.YouWorkflowImpl
          activity-beans:
            - activity-bean-name1
          capacity:
            max-concurrent-workflow-task-executors: 1
            max-concurrent-activity-executors: 1
            max-concurrent-local-activity-executors: 1
            max-concurrent-workflow-task-pollers: 3
            max-concurrent-activity-task-pollers: 3
          rate-limits:
            max-worker-activities-per-second: 2.0
            max-task-queue-activities-per-second: 2.0
        # build-id:
          # worker-build-id: "1.0.0"
        - task-queue: other-task-queue
          # name: your-worker-name # unique name of the Worker. If not specified, Task Queue is used as the Worker name.
          workflow-classes:
            - your.package.YouWorkflowImpl
          activity-beans:
            - activity-bean-name1
          capacity:
            max-concurrent-workflow-task-executors: 2
            max-concurrent-activity-executors: 2
            max-concurrent-local-activity-executors: 2
            max-concurrent-workflow-task-pollers: 5
            max-concurrent-activity-task-pollers: 5
          rate-limits:
            max-worker-activities-per-second: 3.0
            max-task-queue-activities-per-second: 3.0
          # build-id:
          # worker-build-id: "1.0.0"
    workflow-cache:
      max-instances: 242
      max-threads: 0
  # workersAutoDiscovery:
  #   packages: io.temporal.samples.springboot

# actuator (sdk metrics)
management:
  endpoints:
    web:
      exposure:
        include: prometheus